PROJECT_NAME         = "5hash"
ENVIRONMENT          = "dev"
LOCATION             = "northeurope"
RESOURCE_GROUP_NAME  = "rg-5hash-dev-northeurope"
MYSQL_ADMIN_LOGIN    = "taylorShift"
MYSQL_ADMIN_PASSWORD = "Mypassword100!"
