apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
  namespace: app
  labels:
    app: prestashop
spec:
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - name: prestashop
          env:
            - name: PORT
              value: "8080"
            - name: DB_USER
              value: "taylorShift@sqlserver-5hash-dev-northeurope"
            - name: DB_PASSWD
              value: "Mypassword100!"
            - name: DB_NAME
              value: "sqlserver-5hash-dev-northeurope"
            - name: DB_SERVER
              value: "sqlserver-5hash-dev-northeurope.mysql.database.azure.com"
            - name: ADMIN_MAIL 
              value: "taylorShift"
            - name: ADMIN_PASSWD 
              value: "Mypassword100!"
            - name: PS_HOST_MODE
              value: "1"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/"
              port: 8080
