apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service-configmap.yaml

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: prestashop
  - path: autoscale.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: prestashop
