# this configMap should be added by the CI/CD pipeline
apiVersion: v1
kind: ConfigMap
metadata:
  name: prestashop-config
  namespace: app
data:
  PORT: "8080"
  DB_USER: "taylorShift@sqlserver-5hash-rec-northeurope"
  DB_PASSWD: "Mypassword100!"
  DB_NAME: "prestashopdbrec"
  DB_SERVER: "sqlserver-5hash-rec-northeurope.mysql.database.azure.com"
  ADMIN_MAIL: "taylorShift@gmail.com"
  ADMIN_PASSWD: "Mypassword100!"
  PS_INSTALL_AUTO: "1"
  PS_HANDLE_DYNAMIC_DOMAIN: "1"
